name: CI
on:
  push:
    branches: [master]
jobs:
  unit-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone the project
        uses: actions/checkout@v2
      - name: Use node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install deps
        run: npm ci
      - name: Run tests
        run: npm run test
